# Generated by Django 5.2.6 on 2025-09-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=50)),
                ("branch", models.CharField(max_length=20)),
            ],
        ),
    ]
